GET http://localhost:3000/api/vapi/generate


POST http://localhost:3000/api/vapi/generate
Content-Type: application/json
{
 "role":"frontend",
 "type":"mixed",
 "level":"junior",
 "techstack":"next.js",
 "amount":"3",
 "userid":"tVXbGqQ94sWCPhR9wtuGo33DsZ83"
}